name: CI

on:
  workflow_dispatch:
  #pull_request:
  #push:
  #  branches:
  #    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in $(seq 1 5); do
            false && s=0 && break || s=$? && sleep 15;
          done;
          (exit $s)
