name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const labels = (await github.paginate(github.rest.issues.listLabelsOnIssue, {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })).map(label => label.name)
            
            if (labels.includes("do-not-merge")) core.setFailed("do-not-merge label exists")
