name: Merge Check

on:
  pull_request:
    types: [ labeled, unlabeled ]

jobs:
  check:
    if: ${{ github.event.label.name == 'do-not-merge' }}
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
